=== BGCX067/fakocka-svn-to-git/trunk/fakocka/src/fakocka/circuit.dtd
<?xml version="1.0"?>
<!DOCTYPE circuit [
<!ATTLIST circuit ver NMTOKEN #REQUIRED>
<!ELEMENT circuit (composite*,component+)>
<!ELEMENT composite (cid,parts)><!-- kompozit elem -->
<!ELEMENT cid (#PCDATA)>
<!ELEMENT parts (component+)>
<!ELEMENT component (id,type,(pincount|value|connections|reference)?)><!-- komponens -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT pincount (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT reference (#PCDATA)>
<!ELEMENT connections (in,out)>
<!ELEMENT in (id,pin)>
<!ELEMENT out (id,pin)>
]>

=== BGCX067/fakocka-svn-to-git/branches/xml/teszteset2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuit SYSTEM "circuit.dtd">
<circuit ver="1.0">

<component><!-- jelgenerator -->
 <id>0</id>
 <type>switch</type>
 <value>1</value>
</component>

<component><!-- kijelzo -->
 <id>1</id>
 <type>display</type>
</component>

<component><!-- vezetek a jelgenerator kimenete es a kijelzo bemenete kozott -->
 <id>2</id>
 <type>wire</type>
 <connections>
  <in>
   <id>0</id>
   <pin>0</pin>
  </in>
  <out>
   <id>1</id>
   <pin>0</pin>
  </out>
 </connections>
</component>

</circuit>

=== BGCX067/fakocka-svn-to-git/tags/xml/01_SignalGenerator_Scope.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE circuit SYSTEM "circuit.dtd"> -->
<circuit ver="1.0">

<component><!-- jelgenerator -->
 <id>0</id>
 <type>signalgenerator</type>
 <value>1010</value>
</component>

<component><!-- oszcilloszkop-->
 <id>1</id>
 <type>scope</type>
</component>

<component><!-- vezetek a jelgenerator kimenete es az oszcilloszkop bemenete kozott -->
 <id>2</id>
 <type>wire</type>
 <connections>
  <in>
   <id>0</id>
   <pin>0</pin>
  </in>
  <out>
   <id>1</id>
   <pin>0</pin>
  </out>
 </connections>
</component>

</circuit>

=== BGCX067/fakocka-svn-to-git/tags/xml/11_1_bit_MPX.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuit SYSTEM "circuit.dtd">
<circuit ver="1.0">
<composite>
		<!-- egy bites mpx -->
		<cid>0</cid>
		<parts>
			<component>
				<!-- kapcsolo -->
				<id>0</id>
				<type>switch</type>
				<value>0</value>
			</component>
			<component>
				<!-- kapcsolo -->
				<id>1</id>
				<type>switch</type>
				<value>0</value>
			</component>
			<component>
				<!-- kapcsolo -->
				<id>2</id>
				<type>switch</type>
				<value>0</value>
			</component>
			<component>
				<!-- csomopont -->
				<id>3</id>
				<type>node</type>
				<pincount>3</pincount>
			</component>
			<component>
				<!-- inverter -->
				<id>4</id>
				<type>inverter</type>
			</component>
			<component>
				<!-- es kapu -->
				<id>5</id>
				<type>andgate</type>
				<pincount>3</pincount>
			</component>
			<component>
				<!-- es kapu -->
				<id>6</id>
				<type>andgate</type>
				<pincount>3</pincount>
			</component>
			<component>
				<!-- vagy kapu -->
				<id>7</id>
				<type>orgate</type>
				<pincount>3</pincount>
			</component>
			<component>
				<!-- display -->
				<id>8</id>
				<type>display</type>
			</component>
			<component>
				<!-- vezetek -->
				<id>9</id>
				<type>wire</type>
				<connections>
					<in>
						<id>1</id>
						<pin>0</pin>
					</in>
					<out>
						<id>3</id>
						<pin>0</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>10</id>
				<type>wire</type>
				<connections>
					<in>
						<id>3</id>
						<pin>1</pin>
					</in>
					<out>
						<id>4</id>
						<pin>0</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>11</id>
				<type>wire</type>
				<connections>
					<in>
						<id>3</id>
						<pin>2</pin>
					</in>
					<out>
						<id>6</id>
						<pin>1</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>12</id>
				<type>wire</type>
				<connections>
					<in>
						<id>4</id>
						<pin>1</pin>
					</in>
					<out>
						<id>5</id>
						<pin>2</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>13</id>
				<type>wire</type>
				<connections>
					<in>
						<id>0</id>
						<pin>0</pin>
					</in>
					<out>
						<id>5</id>
						<pin>1</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>14</id>
				<type>wire</type>
				<connections>
					<in>
						<id>2</id>
						<pin>0</pin>
					</in>
					<out>
						<id>6</id>
						<pin>2</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>15</id>
				<type>wire</type>
				<connections>
					<in>
						<id>5</id>
						<pin>0</pin>
					</in>
					<out>
						<id>7</id>
						<pin>1</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>16</id>
				<type>wire</type>
				<connections>
					<in>
						<id>6</id>
						<pin>0</pin>
					</in>
					<out>
						<id>7</id>
						<pin>2</pin>
					</out>
				</connections>
			</component>
			<component>
				<!-- vezetek -->
				<id>17</id>
				<type>wire</type>
				<connections>
					<in>
						<id>7</id>
						<pin>0</pin>
					</in>
					<out>
						<id>8</id>
						<pin>0</pin>
					</out>
				</connections>
			</component>
		</parts>
	</composite>
	
	<!-- #################################### -->
	<component><!-- kapcsolo -->
	<id>0</id>
	<type>switch</type>
	<value>0</value>
</component>
<component><!-- kapcsolo -->
	<id>1</id>
	<type>switch</type>
	<value>0</value>
</component>
<component><!-- kapcsolo -->
	<id>2</id>
	<type>switch</type>
	<value>0</value>
</component>
<component><!-- composite -->
	<id>3</id>
	<type>composite</type>
	<reference>0</reference>
	<inpins>3</inpins>
	<outpins>1</outpins>
</component>
<component><!-- display -->
	<id>4</id>
	<type>display</type>
</component>
<component><!-- vezetek -->
	<id>5</id>
	<type>wire</type>
	<connections>
		<in>
			<id>0</id>
			<pin>0</pin>
		</in>
		<out>
			<id>3</id>
			<pin>0</pin>
		</out>
	</connections>
</component>
<component><!-- vezetek -->
	<id>6</id>
	<type>wire</type>
	<connections>
		<in>
			<id>1</id>
			<pin>0</pin>
		</in>
		<out>
			<id>3</id>
			<pin>1</pin>
		</out>
	</connections>
</component>
<component><!-- vezetek -->
	<id>7</id>
	<type>wire</type>
	<connections>
		<in>
			<id>2</id>
			<pin>0</pin>
		</in>
		<out>
			<id>3</id>
			<pin>2</pin>
		</out>
	</connections>
</component>
<component><!-- vezetek -->
	<id>8</id>
	<type>wire</type>
	<connections>
		<in>
			<id>3</id>
			<pin>3</pin>
		</in>
		<out>
			<id>4</id>
			<pin>0</pin>
		</out>
	</connections>
</component>
	
</circuit>

=== BGCX067/fakocka-svn-to-git/branches/xml/teszteset6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuit SYSTEM "circuit.dtd">
<circuit ver="1.0">
 
<component><!-- jelgenerator -->
 <id>0</id>
 <type>signalgenerator</type>
 <value>10</value>
</component>
 
<component><!-- csomopont -->
 <id>1</id>
 <type>node</type>
 <pincount>3</pincount>
</component>
 
<component><!-- kijelzo -->
 <id>2</id>
 <type>display</type>
</component>

<component><!-- kijelzo -->
 <id>3</id>
 <type>display</type>
</component>
 
<component><!-- vezetek a jelgenerator0 es a csomopont kozott-->
<id>4</id>
<type>wire</type>
<connections>
 <in>
  <id>0</id>
  <pin>0</pin>
 </in>
 <out>
  <id>1</id>
  <pin>0</pin>
 </out>
</connections>
</component>
 
<component><!-- vezetek a csomopont es display kozott -->
<id>5</id>
<type>wire</type>
<connections>
 <in>
  <id>1</id>
  <pin>1</pin>
 </in>
 <out>
  <id>2</id>
  <pin>0</pin>
 </out>
</connections>
</component>
 
<component><!-- vezetek a csomopont es display kozott -->
<id>6</id>
<type>wire</type>
<connections>
 <in>
  <id>1</id>
  <pin>2</pin>
 </in>
 <out>
  <id>3</id>
  <pin>0</pin>
 </out>
</connections>
</component> 

</circuit>
